### PR TITLE
Add support for optional LANG param

### PR DESCRIPTION
**Pull request by timurgarif**
#16

### CODE REVIEW

**Comment by alexisvisco** [comment]
Hey thanks for your pull request, can you provide a go enum of the language supported by sonic please ? 
It will be nicer for the developers :)

**Comment by timurgarif** [comment]
Oh, good point! I didn't think of it. The only drawback of this approach would be need to maintain the enum every time Sonic adds/removes support for new languages.
I'll do that a little bit later.

Also the PR introduces the public API change. The package has no releases yet (no stable sem versions). So it should be OK?

**Comment by alexisvisco** [comment]
It's not a big deal, developers need to be agile, I am not active on the project so there are some consequences haha :)

**Comment by alexisvisco** [comment]
For maintaining the enum not really, you can override or add an enum since it's a string.

**Comment by alexisvisco** [comment]
If you really want to not introduce a breaking change you can add a Query() without the lang and a QueryWithLang()
Not optimal but it's a solution.

**Comment by timurgarif** [comment]
Nice. Then we'd better to stick to the current API to keep it closer to the original Sonic protocol.

BTW, I amened the PR as you suggested.

**Review by alexisvisco — APPROVED** [review]

**Pull request merged**
